# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HR_calculation(object):
    def setupUi(self, HR_calculation):
        HR_calculation.setObjectName("HR_calculation")
        HR_calculation.resize(328, 169)
        self.centralwidget = QtWidgets.QWidget(HR_calculation)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 301, 111))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.open_file = QtWidgets.QPushButton(self.groupBox)
        self.open_file.setGeometry(QtCore.QRect(140, 20, 151, 23))
        self.open_file.setObjectName("open_file")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(10, 70, 118, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.start = QtWidgets.QCommandLinkButton(self.groupBox)
        self.start.setGeometry(QtCore.QRect(130, 60, 161, 41))
        self.start.setObjectName("start")
        self.day_z = QtWidgets.QLineEdit(self.groupBox)
        self.day_z.setGeometry(QtCore.QRect(90, 20, 31, 21))
        self.day_z.setObjectName("day_z")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label.setObjectName("label")
        HR_calculation.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HR_calculation)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 328, 20))
        self.menubar.setObjectName("menubar")
        HR_calculation.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HR_calculation)
        self.statusbar.setObjectName("statusbar")
        HR_calculation.setStatusBar(self.statusbar)

        self.retranslateUi(HR_calculation)
        QtCore.QMetaObject.connectSlotsByName(HR_calculation)

    def retranslateUi(self, HR_calculation):
        _translate = QtCore.QCoreApplication.translate
        HR_calculation.setWindowTitle(_translate("HR_calculation", "HR_calculation"))
        self.open_file.setText(_translate("HR_calculation", "Оберіть файл"))
        self.start.setText(_translate("HR_calculation", "Почати обробку"))
        self.day_z.setText(_translate("HR_calculation", "31"))
        self.label.setText(_translate("HR_calculation", "Кількість днів:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HR_calculation = QtWidgets.QMainWindow()
    ui = Ui_HR_calculation()
    ui.setupUi(HR_calculation)
    HR_calculation.show()
    sys.exit(app.exec_())
